### ISSUE TITLE
Jenkins fails to start

### ISSUE THREAD

**Issue by bkblain** [ICTO/ansible-jenkins#52]
Ubuntu 16.04
Jenkins 2.19.1

I was running into a problem starting the Jenkins service.

```
Running from: /usr/share/jenkins/jenkins.war
Oct 09, 2016 7:02:16 AM org.eclipse.jetty.util.log.JavaUtilLog info
INFO: Logging initialized @631ms
Oct 09, 2016 7:02:16 AM winstone.Logger logInternal
INFO: Beginning extraction from war file
Oct 09, 2016 7:02:16 AM org.eclipse.jetty.util.log.JavaUtilLog warn
WARNING: Empty contextPath
Oct 09, 2016 7:02:16 AM winstone.Logger logInternal
INFO: Winstone shutdown successfully
Oct 09, 2016 7:02:16 AM winstone.Logger logInternal
SEVERE: Container startup failed
java.io.IOException: Failed to start a listener: winstone.Ajp13ConnectorFactory
        at winstone.Launcher.spawnListener(Launcher.java:207)
        at winstone.Launcher.<init>(Launcher.java:148)
        at winstone.Launcher.main(Launcher.java:352)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at Main._main(Main.java:246)
        at Main.main(Main.java:91)
Caused by: java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:592)
        at java.lang.Integer.parseInt(Integer.java:615)
        at winstone.cmdline.Option.intArg(Option.java:291)
        at winstone.cmdline.Option$OInt.get(Option.java:203)
        at winstone.Ajp13ConnectorFactory.start(Ajp13ConnectorFactory.java:24)
        at winstone.Launcher.spawnListener(Launcher.java:205)
        ... 8 more
```

To get Jenkins to start I went into `/etc/default/jenkins` and removed the `--ajp13Port=$AJP_PORT` from `JENKINS_ARGS`. The `$AJP_PORT` variable does not exist in the current file. The `JENKINS_ARGS` value is set in the config.yml
[https://github.com/ICTO/ansible-jenkins/blob/development/tasks/config.yml#L39](https://github.com/ICTO/ansible-jenkins/blob/development/tasks/config.yml#L39)

**Comment by devjatkin** [comment]
I have the same issue with Debian 8.6 and Jenkins 2.19.2

**Comment by devjatkin** [comment]
I've created a PR #53 , it fixed issue for me
